// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type RegisterReq struct {
	Mobile     string `json:"mobile"`
	VerifyCode string `json:"verify_code"`
}

type RegisterReply struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginReply struct {
	Code        int    `json:"code"`
	Message     string `json:"message"`
	AccessToken string `json:"accessToken"`
}

type CreateAssetsReq struct {
	Type           string  `json:"type"`
	Assets_balance float64 `json:"assets_balance"`
	Account_name   string  `json:"account_name"`
}

type CreateAssetsReply struct {
	Type           string  `json:"type"`
	Assets_balance float64 `json:"assets_balance"`
	Account_name   string  `json:"account_name"`
}

type UpdateAssetsReq struct {
	Id             int64   `path:"id"`
	Type           string  `json:"type"`
	Assets_balance float64 `json:"assets_balance"`
	Account_name   string  `json:"account_name"`
}

type UpdateAssetsReply struct {
	Type           string  `json:"type"`
	Assets_balance float64 `json:"assets_balance"`
	Account_name   string  `json:"account_name"`
}

type DeleteAssetsReq struct {
	Id int64 `path:"id"`
}

type DeleteAssetsReply struct {
	Message string `json:"message"`
}

type GetAssetsReq struct {
	Id int64 `path:"id"`
}

type GetAssetsReqReply struct {
	Type           string  `json:"type"`
	Assets_balance float64 `json:"assets_balance"`
	Account_name   string  `json:"account_name"`
}

type Assets struct {
	Type           string  `json:"type"`
	Assets_balance float64 `json:"assets_balance"`
	Account_name   string  `json:"account_name"`
}

type ListAssetsReply struct {
	Count  int32    `json:"count"`
	Assets []*Assets `json:"assets"`
}

type CreateDebtReq struct {
	Type         string  `json:"type"`
	Debt_amount  float64 `json:"debt_amount"`
	Account_name string  `json:"account_name"`
	//Debt_total   float64 `json:"debt_total"`
}

type CreateDebtReply struct {
	Type         string  `json:"type"`
	Debt_amount  float64 `json:"debt_amount"`
	Account_name string  `json:"account_name"`
	Debt_total   float64 `json:"debt_total"`
}
